# SMS Spam Collection Dataset

### 1. DESCRIPTION
--------------

The SMS Spam Collection v.1 (hereafter the corpus) is a set of SMS tagged messages that have been collected for SMS Spam research. It contains one set of SMS messages in English of 5,574 messages, tagged acording being ham (legitimate) or spam. 

#### 1.1. Compilation
----------------

This corpus has been collected from free or free for research sources at the Web:

- A collection of between 425 SMS spam messages extracted manually from the Grumbletext Web site. This is a UK forum in which cell phone users make public claims about SMS spam messages, most of them without reporting the very spam message received. The identification of the text of spam messages in the claims is a very hard and time-consuming task, and it involved carefully scanning hundreds of web pages. The Grumbletext Web site is: http://www.grumbletext.co.uk/
- A list of 450 SMS ham messages collected from Caroline Tag's PhD Theses available at http://etheses.bham.ac.uk/253/1/Tagg09PhD.pdf
- A subset of 3,375 SMS ham messages of the NUS SMS Corpus (NSC), which is a corpus of about 10,000 legitimate messages collected for research at the Department of Computer Science at the National University of Singapore. The messages largely originate from Singaporeans and mostly from students attending the University. These messages were collected from volunteers who were made aware that their contributions were going to be made publicly available. The NUS SMS Corpus is avalaible at: http://www.comp.nus.edu.sg/~rpnlpir/downloads/corpora/smsCorpus/
- The amount of 1,002 SMS ham messages and 322 spam messages extracted from the SMS Spam Corpus v.0.1 Big created by Jos?Mar? G?ez Hidalgo and public available at: http://www.esp.uem.es/jmgomez/smsspamcorpus/


#### 1.2. Statistics
---------------

There is one collection:

- The SMS Spam Collection v.1 (text file: smsspamcollection) has a total of 4,827 SMS legitimate messages (86.6%) and a total of 747 (13.4%) spam messages.


#### 1.3. Format
-----------

The files contain one message per line. Each line is composed by two columns: one with label (ham or spam) and other with the raw text. Here are some examples:

ham   What you doing?how are you?
ham   Ok lar... Joking wif u oni...
ham   dun say so early hor... U c already then say...
ham   MY NO. IN LUTON 0125698789 RING ME IF UR AROUND! H*
ham   Siva is in hostel aha:-.
ham   Cos i was out shopping wif darren jus now n i called him 2 ask wat present he wan lor. Then he started guessing who i was wif n he finally guessed darren lor.
spam   FreeMsg: Txt: CALL to No: 86888 & claim your reward of 3 hours talk time to use from your phone now! ubscribe6GBP/ mnth inc 3hrs 16 stop?txtStop
spam   Sunshine Quiz! Win a super Sony DVD recorder if you canname the capital of Australia? Text MQUIZ to 82277. B
spam   URGENT! Your Mobile No 07808726822 was awarded a L2,000 Bonus Caller Prize on 02/09/03! This is our 2nd attempt to contact YOU! Call 0871-872-9758 BOX95QU

Note: messages are not chronologically sorted.


### 2. USAGE
--------

We offer a comprehensive study of this corpus in the following paper that is under review. This work presents a number of statistics, studies and baseline results for several machine learning methods.

[1] Almeida, T.A., G?ez Hidalgo, J.M., Yamakami, A. Contributions to the study of SMS Spam Filtering: New Collection and Results. Proceedings of the 2011 ACM Symposium on Document Engineering (ACM DOCENG'11), Mountain View, CA, USA, 2011. (Under review)


### 3. ABOUT
--------

The corpus has been collected by Tiago Agostinho de Almeida (http://www.dt.fee.unicamp.br/~tiago) and Jos?Mar? G?ez Hidalgo (http://www.esp.uem.es/jmgomez).

We would like to thank Dr. Min-Yen Kan (http://www.comp.nus.edu.sg/~kanmy/) and his team for making the NUS SMS Corpus available. See: http://www.comp.nus.edu.sg/~rpnlpir/downloads/corpora/smsCorpus/. He is currently collecting a bigger SMS corpus at: http://wing.comp.nus.edu.sg:8080/SMSCorpus/

### 4. LICENSE/DISCLAIMER
---------------------

We would appreciate if:

- In case you find this corpus useful, please make a reference to previous paper and the web page: http://www.dt.fee.unicamp.br/~tiago/smsspamcollection/ in your papers, research, etc.
- Send us a message to tiago@dt.fee.unicamp.br in case you make use of the corpus.

The SMS Spam Collection v.1 is provided for free and with no limitations excepting:

1. Tiago Agostinho de Almeida and Jos?Mar? G?ez Hidalgo hold the copyrigth (c) for the SMS Spam Collection v.1.

2. No Warranty/Use At Your Risk. 

3. Limitation of Liability.

## 패키지 및 모듈 설치
- pandas, numpy, nltk, scikit-learn(sklearn)
- nltk를 import 한 후에는 stopwords 다운로드(한번만)

### Import modules

In [1]:
import pandas as pd
import numpy as np
import nltk
import re
from nltk.corpus import stopwords

# re: Regular expression operations

In [2]:
#nltk.download('stopwords')

### 데이터 읽기

In [3]:
df = pd.read_table("SMSSpamCollection",header=None,sep="\t")
df.head()

0                                                  1
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
# 변수명(Column) 변경
df = df.rename(columns={0: 'label',1: 'messages'})
df.head()

label                                           messages
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

## 데이터 전처리

결측값이 없다는 가정 하에 처리되는 프로그램이 있음 

ex) 지도에 표시

In [6]:
# 결측자료 확인
df.isnull().sum()

label       0
messages    0
dtype: int64

### Stopwords(불용어) 제거

In [13]:
STOPWORDS = set(stopwords.words('english'))

def 불용어제거(텍스트):
    # 소문자로 변환
    텍스트 = 텍스트.lower()
    # 특수문자 제거
    텍스트 = re.sub(r'[^0-9a-zA-Z]', ' ', 텍스트)
    # 추가 빈 칸 제거
    텍스트 = re.sub(r'\s+', ' ', 텍스트)
    # remove stopwords
    텍스트 = " ".join(word for word in 텍스트.split() if word not in STOPWORDS)
    return 텍스트

### re모듈
- regex: 정규표현식
- 특수문자 처리 용이
- 함수: match, search, findall, finditer, fullmatch, split, sub, subn, compile, purge, escape 등
- sub(패턴, 교체할 문자열, 문자열, 최대 교체 수, 플래그)

In [14]:
# messages에 불용어제거 적용
df['processed'] = df['messages'].apply(불용어제거)
df.head()

label                                           messages  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                           processed  
0  go jurong point crazy available bugis n great ...  
1                            ok lar joking wif u oni  
2  free entry 2 wkly comp win fa cup final tkts 2...  
3                u dun say early hor u c already say  
4             nah think goes usf lives around though

In [15]:
# 데이터 분할(processed => X, label => y)
X = df['processed']
y = df['label']

## BOW(Bag of Words) 인코딩
문서를 숫자 벡터로 변환하는 가장 기본적인 방법

BOW 인코딩 방법에서는 전체 문서 $\{d_1,d_2, \cdots,d_n\}$를 구성하는 고정된 단어장(vocabulary) $\{t_1,t_2,\cdots,t_m\}$를 만들고 $d_i$라는 개별 문서에 단어장에 해당하는 단어들이 포함되어 있는지를 표시하는 방법

$$x_{i,j} = \mbox{문서 } d_i \mbox{내의 단어 } t_j \mbox{의 출현 빈도} $$


Scikit-Learn 문서 전처리 기능
- DictVectorizer: 각 단어의 수를 세어놓은 사전에서 BOW 인코딩 벡터 생성
- CountVectorizer: 문서 집합에서 단어 토큰을 생성하고 각 단어의 수를 세어 BOW 인코딩 벡터
    - 문서를 토큰 리스트로 변환
    - 각 문서에서 토큰의 출현 빈도를 계산(소$\cdot$대문자 구분하지 않음)
    - 각 문서를 BOW 인코딩 벡터로 변환
- TfidfVectorizer: TF-IDF(Term Frequency-Inverse Document Frequency) 방식으로 단어의 가중치를 조정한 BOW 인코딩 벡터 생성

$$ \mbox{TF-IDF}(w) = \mbox{TF}(w) \times \log \left( \frac{N}{\mbox{DF}(w)} \right) $$

- HashingVectorizer: 해시 함수(hash function)을 사용하여 적은 메모리와 빠른 속도로 BOW 인코딩 벡터 생성
- TfidfTransformer: 카운트 행렬을 표준화 된 tf 또는 tf-idf 표현으로 변환

## Model Training

- 데이터를 학습자료와 검증자료로 나눔
- 학습자료를 이용하여 모델 학습
    - CountVectorizer $\longrightarrow$  TfidfTransformer $\longrightarrow$ 설명변수로 모형 적용
- 검증자료로 정확도 계산


In [16]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer

일반적인 과정
``` python
def classify(model, X, y):
    # train test split
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=316, shuffle=True, stratify=y)
    # model training
    model.fit(X_train, y_train)    
    print('Accuracy:', model.score(x_test, y_test)*100)
    cv_score = cross_val_score(model, X, y, cv=5)
    print("CV Score:", np.mean(cv_score)*100)
```

In [17]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=316, shuffle=True, stratify=y)

### sklearn.feature_extraction.text.CountVectorizer
Convert a collection of text documents to a matrix of token counts.

In [18]:
예제문장 =  ['This is the first document.', 'This document is the second document.', 
         'And this is the third one.', 'Is this the first document?']
vectorizer = CountVectorizer()
토큰개수 = vectorizer.fit_transform(예제문장)
vectorizer.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [19]:
print(vectorizer.vocabulary_)

{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}


In [20]:
print(토큰개수.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [21]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
토큰개수2 =  vectorizer2.fit_transform(예제문장)
vectorizer2.get_feature_names_out()

array(['and this', 'document is', 'first document', 'is the', 'is this',
       'second document', 'the first', 'the second', 'the third',
       'third one', 'this document', 'this is', 'this the'], dtype=object)

In [22]:
print(토큰개수2.toarray())

[[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]


In [23]:
단어장 = ['this', 'document', 'first', 'is', 'second', 'the', 'and', 'one'] # 이 단어들의 빈도
vectorizer3 = CountVectorizer(vocabulary=단어장)
토큰개수3 =  vectorizer3.fit_transform(예제문장)
vectorizer3.get_feature_names_out()

array(['this', 'document', 'first', 'is', 'second', 'the', 'and', 'one'],
      dtype=object)

In [24]:
print(토큰개수3.toarray())

[[1 1 1 1 0 1 0 0]
 [1 2 0 1 1 1 0 0]
 [1 0 0 1 0 1 1 1]
 [1 1 1 1 0 1 0 0]]


In [25]:
tfidf = TfidfVectorizer(stop_words = 'english').fit(예제문장) # stop_words 제외하고
print(tfidf.vocabulary_)

{'document': 0, 'second': 1}


In [26]:
print(tfidf.transform(예제문장).toarray()) # 가중치 고려 

[[1.         0.        ]
 [0.78722298 0.61666846]
 [0.         0.        ]
 [1.         0.        ]]


### sklearn.feature_extraction.text.TfidfTransformer
Transform a count matrix to a normalized tf or tf-idf representation

In [27]:
파이프 = Pipeline([('count', CountVectorizer(vocabulary=단어장)),
                 ('tfid', TfidfTransformer())]).fit(예제문장)

In [28]:
토큰개수  = 파이프['count'].transform(예제문장) # 특정 작업을 하게 만들 수 있다

In [29]:
print(토큰개수.toarray())

[[1 1 1 1 0 1 0 0]
 [1 2 0 1 1 1 0 0]
 [1 0 0 1 0 1 1 1]
 [1 1 1 1 0 1 0 0]]


In [30]:
파이프['tfid'].idf_

array([1.        , 1.22314355, 1.51082562, 1.        , 1.91629073,
       1.        , 1.91629073, 1.91629073])

In [31]:
파이프.transform(예제문장).toarray()

array([[0.38408524, 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.38408524, 0.        , 0.        ],
       [0.28108867, 0.6876236 , 0.        , 0.28108867, 0.53864762,
        0.28108867, 0.        , 0.        ],
       [0.31091996, 0.        , 0.        , 0.31091996, 0.        ,
        0.31091996, 0.59581303, 0.59581303],
       [0.38408524, 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.38408524, 0.        , 0.        ]])

In [32]:
def SMS분류(model, X, y):
    # train test split
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=316, shuffle=True, stratify=y)
    # model training
    pipeline_model = Pipeline([('vect', CountVectorizer()),
                               ('tfidf',TfidfTransformer()),
                               ('clf', model)])
    pipeline_model.fit(x_train, y_train)    
    print('Accuracy:', pipeline_model.score(x_test, y_test)*100)    
    
    y_pred = pipeline_model.predict(x_test)
    print(classification_report(y_test, y_pred))
    
    cv_score = cross_val_score(pipeline_model, X, y, cv=5)
    print("CV Score:", np.mean(cv_score)*100)


## Accuracy

혼동행렬(Confusion matrix)

분류 \ 실제 | Positive | Negative
------|--------|--------
Pasitive | TP  | FP
Negative |  FN | TN

- 정확도(accuracy) = (TP+TN)/(TP+FN+FP+TN)
- 정밀도(precision) = TP/(TP+FP)
- 재현율(recall, sensitivity) = TP/(TP+FN)
- F1 = 2 (precision x recall)/(precision+recall)
    - precision과 recall의 조화평균, imbalanced 구조인 경우 많이 사용
- macro: label별 각 합의 평균
- micro: 전체평균

In [33]:
# Logistic regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
SMS분류(model, X, y)

Accuracy: 96.55419956927494
              precision    recall  f1-score   support

         ham       0.96      1.00      0.98      1206
        spam       0.98      0.76      0.86       187

    accuracy                           0.97      1393
   macro avg       0.97      0.88      0.92      1393
weighted avg       0.97      0.97      0.96      1393

CV Score: 96.48235663508065


In [34]:
# Naive Bayes
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
SMS분류(model, X, y)

Accuracy: 96.98492462311557
              precision    recall  f1-score   support

         ham       0.97      1.00      0.98      1206
        spam       1.00      0.78      0.87       187

    accuracy                           0.97      1393
   macro avg       0.98      0.89      0.93      1393
weighted avg       0.97      0.97      0.97      1393

CV Score: 96.93101255122333


In [35]:
# Support Vector Machine
from sklearn.svm import SVC
model = SVC(C=3)
SMS분류(model, X, y)

Accuracy: 98.42067480258436
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1206
        spam       1.00      0.88      0.94       187

    accuracy                           0.98      1393
   macro avg       0.99      0.94      0.96      1393
weighted avg       0.98      0.98      0.98      1393

CV Score: 98.15137145663428


In [36]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
SMS분류(model, X, y)

Accuracy: 97.4156496769562
              precision    recall  f1-score   support

         ham       0.97      1.00      0.99      1206
        spam       0.99      0.81      0.89       187

    accuracy                           0.97      1393
   macro avg       0.98      0.91      0.94      1393
weighted avg       0.97      0.97      0.97      1393

CV Score: 97.50529341201664


In [37]:
def SMS예측(model, x_train, y_train, x_test):
    pipeline_model = Pipeline([('vect', CountVectorizer()),
                               ('tfidf',TfidfTransformer()),
                               ('clf', model)])
    pipeline_model.fit(x_train, y_train)    
    y_pred = pipeline_model.predict(x_test)
    return y_pred

In [38]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=316, shuffle=True, stratify=y)

In [39]:
model = SVC(C=3)
예측label = SMS예측(model, x_train, y_train, x_test)

In [40]:
print(type(y_test),type(예측label))

<class 'pandas.core.series.Series'> <class 'numpy.ndarray'>


In [41]:
print(list(y_test[:10]))
print(예측label[:10])

['ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham']
['ham' 'ham' 'ham' 'ham' 'spam' 'ham' 'ham' 'ham' 'spam' 'ham']


In [42]:
from sklearn.metrics import confusion_matrix
혼동행렬 = confusion_matrix(y_test, 예측label)
print(혼동행렬)

[[1206    0]
 [  22  165]]


In [43]:
from sklearn.metrics import precision_score, recall_score, f1_score

print("Precision:",precision_score(y_test, 예측label, pos_label="ham"))
print("Recall:",recall_score(y_test, 예측label, pos_label="ham"))
print("F1:",f1_score(y_test, 예측label, pos_label="ham"))      

Precision: 0.9820846905537459
Recall: 1.0
F1: 0.9909613804437141


### 개선방안 마련
- TF-IDF 방식 이외의 방법으로 임베딩
- 적용된 모형에서는 default 옵션 사용했는데 옵션 변경

### 기계학습의 문제점
- 딥러닝을 시행했을 때, 뭘 완벽하게 예측할 수 있다고?
- 근데 그게 의미가 있나?
- 

### 한글자료인 경우에 추가적으로 해야 하는 작업은?